### PR TITLE
Simple fix which adds ability to style component or whatever by className

### PR DESCRIPTION
**Pull request by RIP21**
Don't fix anything in particular, but make a behavior of the component more predictable since all other components usually inherit className passed into it as prop. Before a fix, it just swallows it.

### CODE REVIEW

**Comment by RIP21** [comment]
@benrlodge hey man. Please review this one and Pull Request of another guy and deploy newer version.
Thanks :)

**Comment by benrlodge** [comment]
sorry @RIP21 been a little busy lately. do you have any interest taking over this project?

**Comment by RIP21** [comment]
@benrlodge all I can do it's to add some fixes since I use this component and encounter some bugs over and over again :) All fixes I add here as a pull request.
I don't know the procedure of how to post stuff on npm and update versions :) But if you are busy doing so and busy reviewing pull requests I can help with this, no problem.
Be sure, that for each bug I will create an issue, and close it via separate pull request.

**Comment by RIP21** [comment]
@benrlodge ping-pong :P Just reminder to maybe approve this pull request :)

**Comment by benrlodge** [comment]
sorry for the delay, all set @RIP21

**Pull request merged**
